-- =====================================================================
-- HUB 8.0 — Schema inicial (Microsoft SQL Server)
-- Equivalente funcional de database/migrations/db2/001_initial_schema.sql
-- Diferenças: IDENTITY(1,1) em vez de GENERATED ALWAYS AS IDENTITY,
-- BIT em vez de SMALLINT+CHECK, NVARCHAR para texto, DATETIME2 para timestamps,
-- NVARCHAR(MAX) em vez de CLOB.
-- =====================================================================

CREATE TABLE USERS (
  ID              INT IDENTITY(1,1) PRIMARY KEY,
  USERNAME        NVARCHAR(80)  NOT NULL,
  EMAIL           NVARCHAR(160) NULL,
  PASSWORD_HASH   NVARCHAR(255) NOT NULL,
  DISPLAY_NAME    NVARCHAR(160) NOT NULL,
  ACTIVE          BIT NOT NULL DEFAULT 1,
  CREATED_AT      DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UPDATED_AT      DATETIME2 NULL,
  CREATED_BY      INT NULL,
  UPDATED_BY      INT NULL,
  CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE ROLES (
  ID          INT IDENTITY(1,1) PRIMARY KEY,
  CODE        NVARCHAR(40)  NOT NULL,
  NAME        NVARCHAR(120) NOT NULL,
  ACTIVE      BIT NOT NULL DEFAULT 1,
  CREATED_AT  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT UQ_ROLES_CODE UNIQUE (CODE)
);

CREATE TABLE PERMISSIONS (
  ID          INT IDENTITY(1,1) PRIMARY KEY,
  CODE        NVARCHAR(80)  NOT NULL,
  DESCRIPTION NVARCHAR(255) NULL,
  CONSTRAINT UQ_PERMISSIONS_CODE UNIQUE (CODE)
);

CREATE TABLE USER_ROLES (
  USER_ID INT NOT NULL,
  ROLE_ID INT NOT NULL,
  CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE
);

CREATE TABLE ROLE_PERMISSIONS (
  ROLE_ID       INT NOT NULL,
  PERMISSION_ID INT NOT NULL,
  CONSTRAINT PK_ROLE_PERMS PRIMARY KEY (ROLE_ID, PERMISSION_ID),
  CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_RP_PERM FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID) ON DELETE CASCADE
);

CREATE TABLE OPERATIONS (
  ID          INT IDENTITY(1,1) PRIMARY KEY,
  NAME        NVARCHAR(160) NOT NULL,
  DESCRIPTION NVARCHAR(500) NULL,
  ACTIVE      BIT NOT NULL DEFAULT 1,
  CREATED_AT  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UPDATED_AT  DATETIME2 NULL,
  CREATED_BY  INT NULL,
  UPDATED_BY  INT NULL
);

CREATE TABLE OPERATORS (
  ID              INT IDENTITY(1,1) PRIMARY KEY,
  NAME            NVARCHAR(160) NOT NULL,
  REGISTRATION    NVARCHAR(40) NULL,
  ROLE_LABEL      NVARCHAR(80) NULL,
  OPERATION_ID    INT NULL,
  STATUS          NVARCHAR(20) NOT NULL DEFAULT 'ATIVO',
  ACTIVE          BIT NOT NULL DEFAULT 1,
  CREATED_AT      DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UPDATED_AT      DATETIME2 NULL,
  CREATED_BY      INT NULL,
  UPDATED_BY      INT NULL,
  CONSTRAINT FK_OPERATORS_OPERATION FOREIGN KEY (OPERATION_ID) REFERENCES OPERATIONS(ID)
);

CREATE TABLE SHIFTS (
  ID          INT IDENTITY(1,1) PRIMARY KEY,
  NAME        NVARCHAR(80) NOT NULL,
  START_TIME  TIME NOT NULL,
  END_TIME    TIME NOT NULL,
  ACTIVE      BIT NOT NULL DEFAULT 1,
  CREATED_AT  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE APPS (
  ID              INT IDENTITY(1,1) PRIMARY KEY,
  NAME            NVARCHAR(160) NOT NULL,
  SUBTITLE        NVARCHAR(200) NULL,
  DESCRIPTION     NVARCHAR(500) NULL,
  CATEGORY        NVARCHAR(60) NULL,
  ICON            NVARCHAR(120) NULL,
  URL             NVARCHAR(255) NOT NULL,
  STATUS          NVARCHAR(20) NOT NULL DEFAULT 'ATIVO',
  SORT_ORDER      INT NOT NULL DEFAULT 0,
  MIN_ROLE_ID     INT NULL,
  ACTIVE          BIT NOT NULL DEFAULT 1,
  CREATED_AT      DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UPDATED_AT      DATETIME2 NULL,
  CREATED_BY      INT NULL,
  UPDATED_BY      INT NULL,
  CONSTRAINT FK_APPS_MIN_ROLE FOREIGN KEY (MIN_ROLE_ID) REFERENCES ROLES(ID)
);

CREATE TABLE APP_OPERATORS (
  APP_ID      INT NOT NULL,
  OPERATOR_ID INT NOT NULL,
  CONSTRAINT PK_APP_OPERATORS PRIMARY KEY (APP_ID, OPERATOR_ID),
  CONSTRAINT FK_AO_APP FOREIGN KEY (APP_ID) REFERENCES APPS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_AO_OPERATOR FOREIGN KEY (OPERATOR_ID) REFERENCES OPERATORS(ID) ON DELETE CASCADE
);

CREATE TABLE APP_OPERATIONS (
  APP_ID       INT NOT NULL,
  OPERATION_ID INT NOT NULL,
  CONSTRAINT PK_APP_OPERATIONS PRIMARY KEY (APP_ID, OPERATION_ID),
  CONSTRAINT FK_AOP_APP FOREIGN KEY (APP_ID) REFERENCES APPS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_AOP_OPERATION FOREIGN KEY (OPERATION_ID) REFERENCES OPERATIONS(ID) ON DELETE CASCADE
);

CREATE TABLE AUDIT_LOG (
  ID          INT IDENTITY(1,1) PRIMARY KEY,
  USER_ID     INT NULL,
  DATE_TIME   DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  ACTION      NVARCHAR(40)  NOT NULL,
  ENTITY      NVARCHAR(60)  NOT NULL,
  ENTITY_ID   NVARCHAR(60) NULL,
  OLD_VALUE   NVARCHAR(MAX) NULL,
  NEW_VALUE   NVARCHAR(MAX) NULL,
  IP          NVARCHAR(64) NULL,
  USER_AGENT  NVARCHAR(255) NULL,
  SOURCE      NVARCHAR(40) NULL
);

CREATE TABLE SYSTEM_SETTINGS (
  ID            INT IDENTITY(1,1) PRIMARY KEY,
  SETTING_KEY   NVARCHAR(80) NOT NULL,
  SETTING_VALUE NVARCHAR(1000) NULL,
  UPDATED_AT    DATETIME2 NULL,
  UPDATED_BY    INT NULL,
  CONSTRAINT UQ_SETTINGS_KEY UNIQUE (SETTING_KEY)
);

CREATE TABLE BACKUP_METADATA (
  ID                  INT IDENTITY(1,1) PRIMARY KEY,
  VERSION             NVARCHAR(20) NOT NULL,
  SCHEMA_VERSION      NVARCHAR(20) NOT NULL,
  APPLICATION_VERSION NVARCHAR(20) NOT NULL,
  CREATED_AT          DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CREATED_BY          INT NULL,
  FILE_REF            NVARCHAR(255) NULL
);

CREATE INDEX IX_OPERATORS_OPERATION ON OPERATORS(OPERATION_ID);
CREATE INDEX IX_APPS_STATUS ON APPS(STATUS);
CREATE INDEX IX_AUDIT_ENTITY ON AUDIT_LOG(ENTITY, ENTITY_ID);
CREATE INDEX IX_AUDIT_USER ON AUDIT_LOG(USER_ID);
