-- =====================================================================
-- HUB 8.0 — Schema inicial (IBM DB2 / LUW)
-- Convenções: identificadores em maiúsculas, GENERATED ALWAYS AS IDENTITY,
-- TIMESTAMP para auditoria, soft delete via ACTIVE.
-- =====================================================================

CREATE TABLE USERS (
  ID              INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  USERNAME        VARCHAR(80)  NOT NULL,
  EMAIL           VARCHAR(160),
  PASSWORD_HASH   VARCHAR(255) NOT NULL,
  DISPLAY_NAME    VARCHAR(160) NOT NULL,
  ACTIVE          SMALLINT NOT NULL DEFAULT 1 CHECK (ACTIVE IN (0,1)),
  CREATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  UPDATED_AT      TIMESTAMP,
  CREATED_BY      INTEGER,
  UPDATED_BY      INTEGER,
  CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE ROLES (
  ID          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CODE        VARCHAR(40)  NOT NULL,
  NAME        VARCHAR(120) NOT NULL,
  ACTIVE      SMALLINT NOT NULL DEFAULT 1 CHECK (ACTIVE IN (0,1)),
  CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  CONSTRAINT UQ_ROLES_CODE UNIQUE (CODE)
);

CREATE TABLE PERMISSIONS (
  ID          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CODE        VARCHAR(80)  NOT NULL,
  DESCRIPTION VARCHAR(255),
  CONSTRAINT UQ_PERMISSIONS_CODE UNIQUE (CODE)
);

CREATE TABLE USER_ROLES (
  USER_ID INTEGER NOT NULL,
  ROLE_ID INTEGER NOT NULL,
  CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE
);

CREATE TABLE ROLE_PERMISSIONS (
  ROLE_ID       INTEGER NOT NULL,
  PERMISSION_ID INTEGER NOT NULL,
  CONSTRAINT PK_ROLE_PERMS PRIMARY KEY (ROLE_ID, PERMISSION_ID),
  CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE,
  CONSTRAINT FK_RP_PERM FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID) ON DELETE CASCADE
);

CREATE TABLE OPERATIONS (
  ID          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME        VARCHAR(160) NOT NULL,
  DESCRIPTION VARCHAR(500),
  ACTIVE      SMALLINT NOT NULL DEFAULT 1 CHECK (ACTIVE IN (0,1)),
  CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  UPDATED_AT  TIMESTAMP,
  CREATED_BY  INTEGER,
  UPDATED_BY  INTEGER
);

CREATE TABLE OPERATORS (
  ID              INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME            VARCHAR(160) NOT NULL,
  REGISTRATION    VARCHAR(40),
  ROLE_LABEL      VARCHAR(80),
  OPERATION_ID    INTEGER,
  STATUS          VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
  ACTIVE          SMALLINT NOT NULL DEFAULT 1 CHECK (ACTIVE IN (0,1)),
  CREATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  UPDATED_AT      TIMESTAMP,
  CREATED_BY      INTEGER,
  UPDATED_BY      INTEGER,
  CONSTRAINT FK_OPERATORS_OPERATION FOREIGN KEY (OPERATION_ID) REFERENCES OPERATIONS(ID)
);

CREATE TABLE SHIFTS (
  ID          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME        VARCHAR(80) NOT NULL,
  START_TIME  TIME NOT NULL,
  END_TIME    TIME NOT NULL,
  ACTIVE      SMALLINT NOT NULL DEFAULT 1 CHECK (ACTIVE IN (0,1)),
  CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
);

CREATE TABLE APPS (
  ID              INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME            VARCHAR(160) NOT NULL,
  SUBTITLE        VARCHAR(200),
  DESCRIPTION     VARCHAR(500),
  CATEGORY        VARCHAR(60),
  ICON            VARCHAR(120),
  URL             VARCHAR(255) NOT NULL,
  STATUS          VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
  SORT_ORDER      INTEGER NOT NULL DEFAULT 0,
  MIN_ROLE_ID     INTEGER,
  ACTIVE          SMALLINT NOT NULL DEFAULT 1 CHECK (ACTIVE IN (0,1)),
  CREATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  UPDATED_AT      TIMESTAMP,
  CREATED_BY      INTEGER,
  UPDATED_BY      INTEGER,
  CONSTRAINT FK_APPS_MIN_ROLE FOREIGN KEY (MIN_ROLE_ID) REFERENCES ROLES(ID)
);

CREATE TABLE APP_OPERATORS (
  APP_ID      INTEGER NOT NULL,
  OPERATOR_ID INTEGER NOT NULL,
  CONSTRAINT PK_APP_OPERATORS PRIMARY KEY (APP_ID, OPERATOR_ID),
  CONSTRAINT FK_AO_APP FOREIGN KEY (APP_ID) REFERENCES APPS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_AO_OPERATOR FOREIGN KEY (OPERATOR_ID) REFERENCES OPERATORS(ID) ON DELETE CASCADE
);

CREATE TABLE APP_OPERATIONS (
  APP_ID       INTEGER NOT NULL,
  OPERATION_ID INTEGER NOT NULL,
  CONSTRAINT PK_APP_OPERATIONS PRIMARY KEY (APP_ID, OPERATION_ID),
  CONSTRAINT FK_AOP_APP FOREIGN KEY (APP_ID) REFERENCES APPS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_AOP_OPERATION FOREIGN KEY (OPERATION_ID) REFERENCES OPERATIONS(ID) ON DELETE CASCADE
);

CREATE TABLE AUDIT_LOG (
  ID          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID     INTEGER,
  DATE_TIME   TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  ACTION      VARCHAR(40)  NOT NULL,
  ENTITY      VARCHAR(60)  NOT NULL,
  ENTITY_ID   VARCHAR(60),
  OLD_VALUE   CLOB,
  NEW_VALUE   CLOB,
  IP          VARCHAR(64),
  USER_AGENT  VARCHAR(255),
  SOURCE      VARCHAR(40)
);

CREATE TABLE SYSTEM_SETTINGS (
  ID          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SETTING_KEY VARCHAR(80) NOT NULL,
  SETTING_VALUE VARCHAR(1000),
  UPDATED_AT  TIMESTAMP,
  UPDATED_BY  INTEGER,
  CONSTRAINT UQ_SETTINGS_KEY UNIQUE (SETTING_KEY)
);

CREATE TABLE BACKUP_METADATA (
  ID                  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  VERSION             VARCHAR(20) NOT NULL,
  SCHEMA_VERSION      VARCHAR(20) NOT NULL,
  APPLICATION_VERSION VARCHAR(20) NOT NULL,
  CREATED_AT          TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
  CREATED_BY          INTEGER,
  FILE_REF            VARCHAR(255)
);

CREATE INDEX IX_OPERATORS_OPERATION ON OPERATORS(OPERATION_ID);
CREATE INDEX IX_APPS_STATUS ON APPS(STATUS);
CREATE INDEX IX_AUDIT_ENTITY ON AUDIT_LOG(ENTITY, ENTITY_ID);
CREATE INDEX IX_AUDIT_USER ON AUDIT_LOG(USER_ID);
