server.port=${PORT:3000}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
spring.mvc.problemdetails.enabled=false
spring.jackson.default-property-inclusion=always
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
server.tomcat.max-http-form-post-size=2MB
server.tomcat.max-swallow-size=2MB
server.max-http-request-header-size=16KB
